### ISSUE TITLE
重复推文

### ISSUE THREAD

**Issue by PhotonQuantum** [Chi-Task-Force/realskyzh#1]
在每天随机发送推文时，有概率连续两天发送同样的推文。

可能的解决方法：
- 使用类似 Tetris 的 n-bag 机制，每次随机生成一组推文序列，并持久化（以免在重启服务时丢失），且在每个 bag 消耗完成后更新句表并生成新序列。
- 保持一个已发序列，确保和之前的 `<总句数>/2` 天中发送的内容没有重复。

**Comment by YoruCathy** [comment]
已按照 `保持一个已发序列，确保和之前的 <总句数>/2 天中发送的内容没有重复。` 解决。
